/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/chair.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three"
import { useCustomize } from '../context/Customize'
const Chair = (props) => {
  const { nodes, materials } = useGLTF('./models/chair.gltf')
  
  const leatherTextureProps = useTexture({
    // map : "./textures/leather/Leather_008_Base Color.jpg",
    normal : "./textures/leather/Leather_008_Normal.jpg",
    roughness : "./textures/leather/Leather_008_Roughness.jpg",
    aoMap : "./textures/leather/Leather_008_Ambient Occlusion.jpg",
    // aoMap : "./textures/leather/Leather_008_Height.jpg",
    
  })


  
  const fabricTextureProps = useTexture({
    // map : "./textures/fabric/Fabric_Knitted_006_basecolor.jpg",
    normal : "./textures/fabric/Fabric_Knitted_006_normal.jpg",
    roughness : "./textures/fabric/Fabric_Knitted_006_roughness.jpg",
    aoMap : "./textures/fabric/Fabric_Knitted_006_ambientOcclusion.jpg",
    // aoMap : "./textures/leather/Leather_008_Height.jpg",
    
  })
 
  // leatherTextureProps.map.repeat.set(4,4)
  leatherTextureProps.normal.repeat.set(4,4)
  leatherTextureProps.roughness.repeat.set(4,4)
  leatherTextureProps.aoMap.repeat.set(4,4)


  // leatherTextureProps.map.wrapS =   leatherTextureProps.map.wrapT =
  leatherTextureProps.normal.wrapS =   leatherTextureProps.normal.wrapT =
  leatherTextureProps.roughness.wrapS =   leatherTextureProps.roughness.wrapT =
  leatherTextureProps.aoMap.wrapS =   leatherTextureProps.aoMap.wrapT =
  THREE.RepeatWrapping;
 
  // fabricTextureProps.map.repeat.set(3,3)
  fabricTextureProps.normal.repeat.set(3,3)
  fabricTextureProps.roughness.repeat.set(3,3)
  fabricTextureProps.aoMap.repeat.set(3,3)


  // fabricTextureProps.map.wrapS =   fabricTextureProps.map.wrapT =
  fabricTextureProps.normal.wrapS =   fabricTextureProps.normal.wrapT =
  fabricTextureProps.roughness.wrapS =   fabricTextureProps.roughness.wrapT =
  fabricTextureProps.aoMap.wrapS =   fabricTextureProps.aoMap.wrapT =
  THREE.RepeatWrapping;

  const {material , legs ,Cushion ,Chair} = useCustomize()
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chair.geometry}  >
        <meshStandardMaterial 
          {...(material === "leather" ? leatherTextureProps : fabricTextureProps )}
            color={Cushion.color}
          />

      </mesh>
      <mesh geometry={nodes.Cushion.geometry} position={[0, 0.064, 0.045]} >
        <meshStandardMaterial {...fabricTextureProps} color={Chair.color}/>
        </mesh>
      <mesh geometry={nodes.Legs1.geometry} material={materials.Legs} visible={legs === 0 }/>
      <mesh geometry={nodes.Legs2.geometry} material={materials.Legs} visible={legs === 1}/>
    </group>
  )
}

useGLTF.preload('./models/chair.gltf')

export default Chair